server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name v2ray.leazhi.com;

  access_log /usr/local/nginx/logs/access.log main;

  # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
  ssl_certificate /usr/local/ssl/v2ray.leazhi.com/v2ray.leazhi.com_bundle.crt;
  ssl_certificate_key /usr/local/ssl/v2ray.leazhi.com/v2ray.leazhi.com.key;

  ssl_session_cache    shared:SSL:1m;
  ssl_session_timeout  5m;
  ssl_ciphers  HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers  on;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

  add_header Strict-Transport-Security max-age=15768000;

  root /data/nginx/v2ray.leazhi.com;
  index index.htm index.html;

  #if ( $scheme = http ) {
  if ( $ssl_protocol = "" ) {
      rewrite ^ https://$host$request_uri?;
  }

  location / {
    root /data/nginx/v2ray.leazhi.com;
    index index.htm index.html;
  }
}